version: '3'

services:
  swoole:
    # image: phpswoole/swoole:latest
    image: phpswoole/swoole:4.5.2-php7.4
    environment:
      - DOCKER=1
      - HOST=0.0.0.0
      - HOSTNAME=docker.local
      - PORT=8080
      - SWOOLE_HTTP_HOST=0.0.0.0 # required for Laravel swoole
      - SWOOLE_HTTP_WEBSOCKET=true # required for Laravel swoole websocket
    command: php /workdir/serve-file.php start
    # command: php /workdir/client.php start # broken without additional async extension
    # command: php /workdir/channel.php start # broken without additional async extension
    # command: php /workdir/process.php start
    # command: php /workdir/router.php start
    # command: php /workdir/websocket.php start
    # command: php /workdir/slim.php start
    # command: php /workdir/event-source.php start
    # command: php /workdir/users/artisan serve --host=0.0.0.0 --port=1215 # Laravel no swoole
    # command: php /workdir/users/artisan swoole:http start # Laravel with swoole
    ports:
      - "8080:8080"
      - "1215:1215" # Laravel port
    volumes:
      - ./:/workdir
